/*

Given a string of length n, generate all of its subsequences. 

A subsequence of a given string (sequence) is a string (sequence) that is generated by 
removing zero or more characters from the given string (sequence) without changing its 
order.

Example
	
	Input : inp[] = "abc"
	Output: ["", "c", "b", "bc", "a", "ac", "ab", "abc"]

Constraints
 
  1 < n < 10

*/

#include<iostream>

using namespace std;

void generateSubsequences(char* inp, char* out, int i, int j) {

	// base case
	if(inp[i] == '\0') { // or i == n
		out[j] = '\0';
		cout << out << endl;
		return;
	}

	// recursive case

	// generate all the subsequences of inp[i...n-1] i.e. take a sequence of (n-i) decision

	// take a decision for the character at the ith index

	// 1. include the ith character to the output subseq.
	out[j] = inp[i];
	generateSubsequences(inp, out, i+1, j+1);

	// 2. exclude the ith character from the output subseq.
	generateSubsequences(inp, out, i+1, j);

} 

int main() {

	char inp[] = "abc";
	char out[10];

	generateSubsequences(inp, out, 0, 0);
	
	return 0;
}
